package com.example.mobiilikehitysprojekti.tetris_constants

enum class CellConstants(val value: Byte) {
    EMPTY(0), EPHEMERAL(1)
}
//This code is to help manipulate the generated bytes of the block